'use strict';
const C=Calculations,$=id=>document.getElementById(id),v=id=>$(id)?.value??'';
const fmt=(x,d=3)=>{if(!Number.isFinite(x))throw Error('Résultat hors du domaine numérique.');if(x!==0&&(Math.abs(x)<10**(-d)||Math.abs(x)>=1e12))return x.toExponential(4).replace('.',',');return x.toLocaleString('fr-FR',{maximumFractionDigits:d});};
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const checks=b=>b===null?'Non vérifié : seuil non renseigné':b?'Sous le seuil saisi':'Seuil saisi dépassé';
const info={
 ajustements:['Jeux & diamètres limites','Jmin = EI trou − es arbre ; Jmax = ES trou − ei arbre. Diamètre limite = diamètre nominal + écart.','Tables intégrées : H6/H7/H8, G6/G7, h6/h7/h8/h9 et g6, de 0 à 500 mm (borne supérieure incluse). Pour toute autre classe, saisissez les écarts de votre table normative. Les écarts manuels restent exprimés en mm.','Tables de tolérances Takayama (JIS B 0401-2, système ISO)','https://www.takayama-industry.com/technology/fitaxis/'],
 vissage:['Précharge & couple estimés','As = π/4 × (d − 0,9382p)² ; F = r × Re × As ; T = K × F × d / 1000.','K est un coefficient global de serrage, distinct du coefficient de frottement. Les valeurs sec/huilé sont indicatives. La précharge totale ne prouve pas la tenue de l’assemblage : rigidités, fatigue, dispersion et charges combinées ne sont pas évaluées.','NASA — Fastener Design Manual','https://ntrs.nasa.gov/citations/19900009424'],
 engrenages:['Géométrie & transmission','d = m × z ; da = m × (z + 2) ; df = m × (z − 2,5) ; a = m × (z₁ + z₂) / 2 ; i = z₂ / z₁ ; n₂ = n₁ / i.','Engrenages extérieurs droits, angle de pression 20°, sans déport de profil, hauteur de tête m et de pied 1,25m. Rotation de sortie en sens inverse. Ce calcul ne vérifie pas la résistance des dents.','KHK — Calculation of Gear Dimensions','https://khkgears.net/gear-knowledge/gear-technical-reference/calculation-gear-dimensions/'],
 torsion:['Contrainte & angle de torsion','J = πd⁴/32 ; τmax = 16|T|/(πd³) ; θ = TL/(GJ). T converti en N·mm, G en MPa.','Arbre cylindrique plein, matériau homogène en domaine élastique, couple statique. Concentrations de contraintes et fatigue non incluses. L’angle conserve le signe du couple ; la contrainte est donnée en valeur absolue.'],
 clavette:['Cisaillement & pression de contact','F = 2|T|/d ; τ = F/(bL) ; p = F/(hL/2). T converti en N·mm.','L est la longueur effectivement en contact, hors extrémités arrondies non porteuses. Appui supposé sur la moitié de la hauteur, répartition uniforme et charge statique.','IIT Kharagpur / NPTEL — Pins and keys','https://archive.nptel.ac.in/content/storage2/courses/112105125/pdf/Module-4_lesson-1.pdf'],
 roulements:['Durée nominale L₁₀','L₁₀ = (C/P)ᵖ × 10⁶ tours ; L₁₀h = L₁₀/(60n). p = 3 pour les billes, 10/3 pour les rouleaux.','Durée de fatigue atteinte ou dépassée par 90 % d’une population comparable, à charge et vitesse constantes. P doit être la charge dynamique équivalente du fabricant. Lubrification, contamination et durée de la graisse non prises en compte.','JTEKT — Calculation of service life','https://koyo.jtekt.co.jp/en/support/bearing-knowledge/5-2000.html'],
 courroie:['Longueur & entraxe','L ≈ 2C + π(D + d)/2 + (D − d)²/(4C). B = L − π(D + d)/2 ; C = [B + √(B² − 2(D − d)²)]/4.','Transmission ouverte, poulies à axes parallèles. Employer des diamètres primitifs et la longueur primitive correspondante. Relation approchée, sans épaisseur ni élasticité ; le dimensionnement en puissance reste à faire.'],
 taraudage:['Diamètre de perçage','Dperçage ≈ Dnominal − pas ; 1 pouce = 25,4 mm.','Estimation pour un taraud coupant métrique. Ne convient pas au taraudage par déformation. Le foret final dépend du matériau, de la tolérance et des recommandations du fabricant ; aucun taux d’engagement universel n’est garanti.','OSG — Tableaux de perçage','https://osgtool.com/literature/charts/'],
 rdm:['Flexion de poutre','Console, force en bout : M = FL ; δ = FL³/(3EI). Console, charge uniforme : M = wL²/2 ; δ = wL⁴/(8EI). Deux appuis, force au milieu : M = FL/4 ; δ = FL³/(48EI). Deux appuis, charge uniforme : M = wL²/8 ; δ = 5wL⁴/(384EI). σmax = |M|c/I.','Poutre droite à section constante, matériau homogène linéaire élastique, petites déformations (Euler–Bernoulli). Poids propre non ajouté. Résultats en valeur absolue. En saisie directe de I, la contrainte ne peut pas être déduite sans la distance à la fibre extrême.'],
 thermo:['Chaleur & gaz parfaits','Q = mc(T₂ − T₁). Gaz parfait : pV = nRT ; avec p en kPa et V en L, pV est en joules.','Chaleur massique constante, sans changement de phase ni pertes thermiques. Pour le gaz parfait, utiliser une pression absolue et une température en kelvins. Le modèle devient inadapté à proximité d’une condensation ou à forte pression.']
};
const slug=location.pathname.split('/').pop().replace('.html','')||'index';
function show(id,rows,note=''){
 const out=$(id);out.classList.remove('error');out.dataset.valid='true';out.innerHTML='<div class="result-heading"><span class="status-dot"></span> RÉSULTATS</div><div class="result-grid">'+rows.map(([label,value,unit=''])=>'<div class="result-item"><span class="result-label">'+escapeHTML(label)+'</span><strong>'+escapeHTML(value)+' <small>'+escapeHTML(unit)+'</small></strong></div>').join('')+'</div>'+(note?'<p class="result-note">'+escapeHTML(note)+'</p>':'');
 const fields=Array.from(document.querySelectorAll('main .card input, main .card select')).filter(el=>(!el.closest('[hidden]')||['EI_hole','ES_hole','EI_shaft','ES_shaft'].includes(el.id))&&(!el.disabled||el.id==='tap_pitch'||['EI_hole','ES_hole','EI_shaft','ES_shaft'].includes(el.id))).filter(el=>slug!=='thermo'||(id==='out_th_heat'?el.id.startsWith('th_'):el.id.startsWith('ig_')));
 out.dataset.inputs=JSON.stringify(fields.map(el=>({label:document.querySelector('label[for="'+el.id+'"]')?.textContent||el.id,value:el.tagName==='SELECT'?el.selectedOptions[0]?.textContent:el.value})));
 out.dataset.time=new Date().toISOString();
}
function run(id,action){try{action();}catch(e){const out=$(id);out.dataset.valid='false';out.classList.add('error');out.textContent=e.message;}}
function calcGear(){run('out_gear',()=>{const r=C.gear(v('gear_m'),v('gear_z1'),v('gear_z2'),v('gear_n1'));show('out_gear',[['Entraxe',fmt(r.a),'mm'],['Vitesse de sortie',fmt(r.n2),'tr/min'],['Rapport de transmission',fmt(r.ratio)],['Ø primitifs · pignon / roue',fmt(r.d1)+' / '+fmt(r.d2),'mm'],['Ø de tête · pignon / roue',fmt(r.da1)+' / '+fmt(r.da2),'mm'],['Ø de pied · pignon / roue',fmt(r.df1)+' / '+fmt(r.df2),'mm']],r.undercut?'Moins de 17 dents : risque de sous-découpe. Vérifier la denture et le déport de profil.':'');});}
function calcTorsion(){run('out_tor',()=>{const r=C.torsion(v('tor_T'),v('tor_d'),v('tor_L'),v('tor_G'),v('tor_tau'));show('out_tor',r.dmin!==undefined?[['Diamètre minimal théorique',fmt(r.dmin,4),'mm']]:[['Contrainte maximale',fmt(r.tau),'MPa'],['Angle de torsion',fmt(r.deg),'°'],['Angle en radians',fmt(r.theta,6),'rad'],['Comparaison au seuil',checks(r.ok)]]);});}
function calcKey(){run('out_key',()=>{const r=C.key(...['kv_T','kv_d','kv_b','kv_h','kv_L','kv_tau','kv_p'].map(v));show('out_key',[['Effort tangentiel',fmt(r.F),'N'],['Cisaillement',fmt(r.tau),'MPa'],['Pression de contact',fmt(r.pressure),'MPa'],['Seuil de cisaillement',checks(r.okTau)],['Seuil de pression',checks(r.okP)]]);});}
function calcBearing(){run('out_bear',()=>{const r=C.bearing(v('br_C'),v('br_P'),v('br_n'),v('br_type')==='3'?'ball':'roller');show('out_bear',[['Durée nominale L₁₀h',fmt(r.hours),'h'],['Durée nominale L₁₀',fmt(r.rev/1e6),'millions de tours']]);});}
function toggleBelt(){if(!$('belt_mode'))return;const length=v('belt_mode')==='LfromC';$('belt_C_box').hidden=!length;$('belt_L_box').hidden=length;}
function calcBelt(){run('out_belt',()=>{toggleBelt();const length=v('belt_mode')==='LfromC',D=v('belt_D'),d=v('belt_d');const result=length?C.beltLength(D,d,v('belt_C')):C.beltCenter(D,d,v('belt_L'));show('out_belt',[[length?'Longueur primitive estimée':'Entraxe estimé',fmt(result), 'mm']]);});}
const COARSE_PITCH={M3:.5,M4:.7,M5:.8,M6:1,M8:1.25,M10:1.5,M12:1.75,M14:2,M16:2,M18:2.5,M20:2.5};
function updateTapPitch(){if(!$('tap_size'))return;const coarse=v('tap_series')==='coarse';if(coarse)$('tap_pitch').value=COARSE_PITCH[v('tap_size')];$('tap_pitch').disabled=coarse;}
function calcTap(){run('out_tap',()=>{const r=C.tap(v('tap_size').replace('M',''),v('tap_pitch'));const rows=[['Perçage théorique',fmt(r.drill),'mm'],['Équivalent en pouces',fmt(r.inch,5),'in']];show('out_tap',v('tap_unit')==='in'?rows.reverse():rows);});}
function rdmToggleSection(){if(!$('rdm_section'))return;document.querySelectorAll('.sec').forEach(el=>el.hidden=!el.classList.contains(v('rdm_section')));const distributed=v('rdm_case').endsWith('udl');document.querySelectorAll('.load.F').forEach(el=>el.hidden=distributed);document.querySelectorAll('.load.w').forEach(el=>el.hidden=!distributed);}
function calcRDM(){run('out_rdm',()=>{const val={};['L','E','b','h','d','I','F','w'].forEach(k=>val[k]=v('rdm_'+k));val.allow=v('rdm_sig');if(v('rdm_unit')==='in'){for(const k of ['L','b','h','d'])if(String(val[k]).trim())val[k]=C.num(val[k],k)*25.4;if(String(val.I).trim())val.I=C.num(val.I,'I')*25.4**4;if(String(val.w).trim())val.w=C.num(val.w,'w')/25.4;}const r=C.beam(v('rdm_case'),v('rdm_section'),val);const rows=[['Flèche maximale',fmt(r.delta,5),'mm'],['Moment maximal',fmt(r.M),'N·mm'],['Moment quadratique I',fmt(r.I),'mm⁴']];if(r.sigma!==null)rows.push(['Contrainte de flexion',fmt(r.sigma),'MPa'],['Comparaison au seuil',checks(r.ok)]);show('out_rdm',rows,r.large?'La flèche dépasse 1 % de la portée. Vérifiez la validité de l’hypothèse de petites déformations.':r.sigma===null?'Contrainte non calculée : distance à la fibre extrême inconnue.':'');});}
function calcThermoHeat(){run('out_th_heat',()=>{const r=C.heat(...['th_m','th_c','th_T1','th_T2'].map(v));show('out_th_heat',[['Énergie thermique',fmt(r.kJ),'kJ'],['Variation de température',fmt(r.delta),'K']],r.Q<0?'Q négatif : chaleur cédée par le système.':'');});}
function toggleIG(){if(!$('ig_unknown'))return;for(const key of ['p','V','n','T'])$('ig_'+key).disabled=key===v('ig_unknown');}
function calcThermoIG(){run('out_th_ig',()=>{const vals={};['p','V','n','T','R'].forEach(k=>vals[k]=v('ig_'+k));const unknown=v('ig_unknown'),r=C.gas(unknown,vals);$('ig_'+unknown).value=String(r[unknown]);show('out_th_ig',[['Pression absolue',fmt(r.p,5),'kPa'],['Volume',fmt(r.V,5),'L'],['Quantité de matière',fmt(r.n,6),'mol'],['Température absolue',fmt(r.T,5),'K']]);});}
const THREADS={M6:[6,1],M8:[8,1.25],M10:[10,1.5],M12:[12,1.75],M16:[16,2]};
function toggleFriction(){if($('K_custom'))$('K_custom').disabled=v('friction')!=='custom';}
function calcBolt(){run('out_vis',()=>{const [d,p]=THREADS[v('thread')],K=v('friction')==='custom'?v('K_custom'):v('friction'),r=C.bolt(d,p,v('grade'),K,v('r_ratio'),v('n_bolts'),v('F_ext'));show('out_vis',[['Couple de serrage estimé',fmt(r.T),'N·m'],['Précharge par vis',fmt(r.F),'N'],['Aire résistante',fmt(r.As),'mm²'],['Précharge totale',fmt(r.total),'N'],['Effort extérieur saisi',fmt(r.Fext),'N']],'Estimation de serrage uniquement. La tenue de l’assemblage sous effort extérieur n’est pas vérifiée.');});}
function refreshISO(){if(!$('mode'))return;const iso=v('mode')==='iso';$('isoFields').hidden=!iso;$('manualFields').hidden=iso;for(const id of ['EI_hole','ES_hole','EI_shaft','ES_shaft'])$(id).disabled=iso;if(!iso){$('isoPreview').textContent='';return;}for(const [id,allowed] of [['hole_it',v('hole_letter')==='G'?['6','7']:['6','7','8']],['shaft_it',v('shaft_letter')==='g'?['6']:['6','7','8','9']]]){for(const option of $(id).options)option.disabled=!allowed.includes(option.value);if(!allowed.includes(v(id)))$(id).value=allowed[0];}try{const D=C.pos(v('D'),'Le diamètre')*(v('unit_len')==='in'?25.4:1),hole=C.deviation(D,v('hole_letter'),v('hole_it')),shaft=C.deviation(D,v('shaft_letter'),v('shaft_it'));for(const [id,x] of [['EI_hole',hole.lower],['ES_hole',hole.upper],['EI_shaft',shaft.lower],['ES_shaft',shaft.upper]])$(id).value=x;$('isoPreview').textContent='Trou : '+fmt(hole.lower,4)+' à '+fmt(hole.upper,4)+' mm · Arbre : '+fmt(shaft.lower,4)+' à '+fmt(shaft.upper,4)+' mm';$('isoPreview').dataset.valid='true';}catch(e){$('isoPreview').textContent=e.message;$('isoPreview').dataset.valid='false';}}
function onDChange(){refreshISO();}
let currentUnit='mm';
function toggleUnitLen(){const next=v('unit_len');if(v('D').trim()){const n=C.num(v('D'),'Le diamètre');$('D').value=String(next===currentUnit?n:next==='in'?n/25.4:n*25.4);}currentUnit=next;const label=document.querySelector('label[for="D"]');if(label)label.textContent='Diamètre nominal D ('+(next==='in'?'in':'mm')+')';refreshISO();}
function calcAjust(){run('out_ajust',()=>{refreshISO();if(v('mode')==='iso'&&$('isoPreview').dataset.valid!=='true')throw Error($('isoPreview').textContent);const D=C.num(v('D'),'Le diamètre')*(v('unit_len')==='in'?25.4:1),r=C.fit(D,...['EI_hole','ES_hole','EI_shaft','ES_shaft'].map(v));show('out_ajust',[['Jeu minimal',fmt(r.min,4),'mm'],['Jeu maximal',fmt(r.max,4),'mm'],['Diamètre du trou · min / max',fmt(r.holeMin,4)+' / '+fmt(r.holeMax,4),'mm'],['Diamètre de l’arbre · min / max',fmt(r.shaftMin,4)+' / '+fmt(r.shaftMax,4),'mm'],['Nature de l’ajustement',r.nature]],'Un jeu négatif correspond à un serrage.');});}
const defaults={};
function resetAll(){for(const [id,value] of Object.entries(defaults))if($(id))$(id).value=value;currentUnit='mm';refreshISO();toggleFriction();rdmToggleSection();toggleIG();toggleBelt();updateTapPitch();clearResults();}
function resetAjust(){resetAll();}function resetBolt(){resetAll();}
function clearResults(){document.querySelectorAll('main [id^="out_"]').forEach(el=>{el.dataset.valid='false';el.classList.remove('error');el.innerHTML='<span class="subtle">Paramètres modifiés. Lancez le calcul pour actualiser les résultats.</span>';});}
function initialize(){
 if(!info[slug])return;
 const main=document.querySelector('main');main.id='main';if($('D'))document.querySelector('label:has(#unitD)').htmlFor='D';
 document.querySelectorAll('main input,main select,main textarea').forEach(el=>{const label=el.previousElementSibling;if(label?.tagName==='LABEL'){label.htmlFor=el.id;label.style.visibility='visible';}defaults[el.id]=el.value;if(el.type==='number'){el.type='text';el.inputMode='decimal';}el.addEventListener('input',clearResults);el.addEventListener('change',clearResults);});
 const [title,formula,note,source,url]=info[slug];
 const card=document.querySelector('main .card');card.querySelector('h2').textContent=title;
 document.querySelectorAll('details').forEach(el=>el.remove());
 const details=document.createElement('details');details.className='reference';details.innerHTML='<summary>Formules & hypothèses</summary><p>'+escapeHTML(formula)+'</p><p>'+escapeHTML(note)+'</p>'+(source?'<a href="'+url+'" target="_blank" rel="noopener">'+escapeHTML(source)+' ↗</a>':'');main.appendChild(details);
 document.querySelectorAll('[id^="out_"]').forEach(el=>{el.innerHTML='<span class="subtle">Renseignez les paramètres puis lancez le calcul.</span>';el.dataset.valid='false';});
 if($('belt_mode'))$('belt_mode').addEventListener('change',toggleBelt);
 if($('friction'))$('friction').addEventListener('change',toggleFriction);
 refreshISO();toggleFriction();rdmToggleSection();rdmLabels();toggleIG();toggleBelt();updateTapPitch();
 main.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('input,select')){const scope=slug==='thermo'?(e.target.id.startsWith('ig_')?'calcThermoIG':'calcThermoHeat'):null;if(scope){e.preventDefault();window[scope]();}else{const button=main.querySelector('button[onclick^="calc"]');if(button){e.preventDefault();button.click();}}}});
 const qs=new URLSearchParams(location.search);let restored=false;for(const [key,value] of qs){const el=$(key);if(el&&el.matches('main input,main select')&&!el.disabled){el.value=value;restored=true;}}
 if(restored){currentUnit=v('unit_len')||'mm';rdmCurrentUnit=v('rdm_unit')||'mm';rdmLabels();refreshISO();toggleFriction();rdmToggleSection();toggleIG();toggleBelt();updateTapPitch();}
 // A useful first result comes from the clearly editable example values.
 const btn=main.querySelector('button[onclick^="calc"]');if(btn)btn.click();if(slug==='thermo')calcThermoIG();
}
document.addEventListener('DOMContentLoaded',initialize);
let rdmCurrentUnit='mm';
function rdmLabels(){if(!$('rdm_unit'))return;const unit=v('rdm_unit');for(const id of ['u_len','u_len_b','u_len_h','u_len_d'])if($(id))$(id).textContent=unit;document.querySelectorAll('[data-unit="I"]').forEach(el=>el.textContent=unit+'⁴');const lab=document.querySelector('label[for="rdm_w"]');if(lab)lab.textContent='Charge répartie w (N/'+unit+')';}
function rdmUnitToggle(){const next=v('rdm_unit');if(next!==rdmCurrentUnit){const f=next==='in'?1/25.4:25.4;for(const id of ['rdm_L','rdm_b','rdm_h','rdm_d'])if(v(id).trim())$(id).value=String(C.num(v(id),'La dimension')*f);if(v('rdm_I').trim())$('rdm_I').value=String(C.num(v('rdm_I'),'I')*f**4);if(v('rdm_w').trim())$('rdm_w').value=String(C.num(v('rdm_w'),'w')/f);rdmCurrentUnit=next;}rdmLabels();}
function updateTapDisplay(){clearResults();}
