/* Linear dimensional stack; millimetres, signed deviations, coefficients ±1. */
(function(root){
'use strict';const C=typeof module==='object'?require('./calculations.js'):root.Calculations;
function calculate(rows,target){if(!Array.isArray(rows)||rows.length<2||rows.length>20)throw Error('Choisissez de 2 à 20 cotes.');let nominal=0,min=0,max=0,center=0;const half=[];
 const parts=rows.map((row,i)=>{const n=C.pos(row.nom,'La cote A'+(i+1),true),lo=C.num(row.lo,'L’écart inférieur A'+(i+1)),hi=C.num(row.hi,'L’écart supérieur A'+(i+1)),sign=C.num(row.sign,'Le sens');if(sign!==1&&sign!==-1)throw Error('Le sens doit être + ou −.');if(lo>hi)throw Error('A'+(i+1)+' : l’écart inférieur dépasse l’écart supérieur.');if(n+lo<0)throw Error('A'+(i+1)+' : la dimension minimale est négative.');const lower=n+lo,upper=n+hi;nominal+=sign*n;min+=sign===1?lower:-upper;max+=sign===1?upper:-lower;center+=sign*(n+lo/2+hi/2);half.push(hi/2-lo/2);return {n,lo,hi,sign};});
 const rss=Math.hypot(...half),result={nominal,min,max,center,rss,rssMin:center-rss,rssMax:center+rss,width:max-min};if(Object.values(result).some(x=>!Number.isFinite(x)))throw Error('Valeurs hors du domaine numérique.');
 let meets=null;if(target){const a=C.num(target.min,'La limite minimale'),b=C.num(target.max,'La limite maximale');if(a>b)throw Error('La limite minimale doit être inférieure ou égale à la limite maximale.');const eps=16*Number.EPSILON*Math.max(1,...parts.map(p=>p.n),Math.abs(a),Math.abs(b));meets=min>=a-eps&&max<=b+eps;}
 return {...result,parts,meets};}
root.ChainCalculations={calculate};if(typeof module==='object')module.exports=root.ChainCalculations;
})(typeof window==='undefined'?globalThis:window);
if(typeof window!=='undefined'){
info.chaines=['Cote de fermeture & tolérances','Pour chaque cote : Lᵢ = Nᵢ + EIᵢ et Uᵢ = Nᵢ + ESᵢ. J nominal = ΣsᵢNᵢ. Jmin = Σ(+)Lᵢ − Σ(−)Uᵢ ; Jmax = Σ(+)Uᵢ − Σ(−)Lᵢ. Centre m = Σsᵢ[Nᵢ + (EIᵢ + ESᵢ)/2]. Demi-largeur RSS = √Σ[(ESᵢ − EIᵢ)/2]² ; plage estimée = m ± RSS.','Chaîne linéaire 1D, pièces rigides, une cote indépendante par pièce, signes ±1. Le pire des cas borne J si chaque cote respecte ses limites et si le modèle représente correctement l’assemblage. RSS : indépendance, distributions normales centrées au milieu des intervalles et demi-largeurs = 3σ. La plage RSS est une estimation ±3σ, pas une garantie de montage ; corrélations, dérives de fabrication, tolérances géométriques et déformations non prises en compte. La condition facultative est toujours vérifiée au pire des cas.','Fritz Scholz (Boeing) — Tolerance Stack Analysis Methods','https://faculty.washington.edu/fscholz/Reports/babytol.pdf'];
window.syncChain=function(){const count=Number(v('ch_count'));document.querySelectorAll('.chain-row').forEach(row=>row.hidden=Number(row.dataset.row)>count);$('chain-rss-note').hidden=v('ch_method')!=='rss';$('chain-diagram').hidden=true;};
window.calcChain=function(){syncChain();run('out_chain',()=>{const count=Number(v('ch_count')),rows=Array.from({length:count},(_,i)=>Object.fromEntries(['nom','lo','hi','sign'].map(k=>[k,v('ch_'+(i+1)+'_'+k)])));const hasTarget=v('ch_min').trim()!==''||v('ch_max').trim()!=='';const r=ChainCalculations.calculate(rows,hasTarget?{min:v('ch_min'),max:v('ch_max')}:null),rss=v('ch_method')==='rss';let output=rss?[['Centre de la plage estimée',fmt(r.center,6),'mm'],['Demi-largeur quadratique',fmt(r.rss,6),'mm'],['Plage RSS estimée · ±3σ',fmt(r.rssMin,6)+' à '+fmt(r.rssMax,6),'mm']]:[['Cote de fermeture nominale J',fmt(r.nominal,6),'mm']];output.push(['J minimal · pire des cas',fmt(r.min,6),'mm'],['J maximal · pire des cas',fmt(r.max,6),'mm'],['Intervalle de tolérance total',fmt(r.width,6),'mm']);if(rss)output.push(['J nominal',fmt(r.nominal,6),'mm']);if(r.meets!==null)output.push(['Condition · au pire des cas',r.meets?'Respectée dans le modèle':'Non garantie sur tout l’intervalle']);show('out_chain',output,rss?'Estimation statistique sous les hypothèses indiquées. Les bornes au pire des cas restent affichées pour comparaison.':'J est une cote algébrique : son signe doit être interprété selon votre assemblage.');drawChain(r);});};
function drawChain(r){const fig=$('chain-diagram'),svg=fig.querySelector('svg');let positions=[0];r.parts.forEach(p=>positions.push(positions.at(-1)+p.sign*p.n));const lo=Math.min(...positions),hi=Math.max(...positions),span=hi-lo||1,x=n=>120+(n-lo)/span*310,height=100+r.parts.length*55;let body='<defs><marker id="chain-tip" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7Z" fill="context-stroke"/></marker></defs>';
 r.parts.forEach((p,i)=>{const y=45+i*55,a=x(positions[i]),b=x(positions[i+1]),color=p.sign===1?'var(--accent)':'#ac65c9';body+='<text x="12" y="'+(y+5)+'">'+(p.sign===1?'+':'−')+' A'+(i+1)+'</text><line x1="'+a+'" x2="'+b+'" y1="'+y+'" y2="'+y+'" stroke="'+color+'" stroke-width="2.5" marker-end="url(#chain-tip)"/><circle cx="'+a+'" cy="'+y+'" r="3" fill="'+color+'"/><text x="'+((a+b)/2)+'" y="'+(y-12)+'" text-anchor="middle">'+escapeHTML(fmt(p.n,4))+'</text>';if(i<r.parts.length-1)body+='<line x1="'+b+'" x2="'+b+'" y1="'+(y+5)+'" y2="'+(y+45)+'" stroke="currentColor" opacity=".25" stroke-dasharray="3 3"/>';});const y=height-40;body+='<text x="12" y="'+(y+5)+'">J</text><line x1="'+x(0)+'" x2="'+x(r.nominal)+'" y1="'+y+'" y2="'+y+'" stroke="var(--accent)" stroke-width="3" marker-end="url(#chain-tip)"/><text x="250" y="'+(height-7)+'" text-anchor="middle">J = '+escapeHTML(fmt(r.nominal,6))+' mm</text>';svg.setAttribute('viewBox','0 0 500 '+height);svg.innerHTML=body;fig.hidden=false;}
document.addEventListener('DOMContentLoaded',()=>{const out=$('out_chain');new MutationObserver(()=>{if(out.dataset.valid!=='true')$('chain-diagram').hidden=true;}).observe(out,{attributes:true,attributeFilter:['data-valid']});document.addEventListener('click',e=>{if(e.target.id==='preset-load')syncChain();});const ref=document.querySelector('.reference');for(const [text,url] of [['H7g6 — principe et calcul de chaînes de cotes','https://www.h7g6.fr/data/article/24/cotation-fonctionnelle'],['Université de Biskra — cotation fonctionnelle','https://www.univ-biskra.dz/enseignant/bensaada/COTATION%20FONCTIONNELLE.pdf']]){const a=document.createElement('a');a.textContent=text+' ↗';a.href=url;a.target='_blank';a.rel='noopener';ref.append(a);}});
}
