/* Engineering models: lengths mm, forces N, moduli GPa. */
(function(root){'use strict';const C=typeof module==='object'?require('./calculations.js'):root.Calculations,p=C.pos;
function checked(r){for(const x of Object.values(r))if(typeof x==='number'&&!Number.isFinite(x))throw Error('Valeurs hors du domaine numérique.');return r;}
function section(shape,a,b,t){a=p(a,'La dimension principale');let A,Ix,Iy,cx,cy;
 if(shape==='circle'||shape==='tube'){const d=shape==='tube'?p(b,'Le diamètre intérieur',true):0;if(d>=a)throw Error('Le diamètre intérieur doit être inférieur au diamètre extérieur.');A=Math.PI*(a*a-d*d)/4;Ix=Iy=Math.PI*(a**4-d**4)/64;cx=cy=a/2;}
 else if(shape==='rect'||shape==='box'){b=p(b,'La hauteur');let bi=0,hi=0;if(shape==='box'){t=p(t,'L’épaisseur');if(2*t>=Math.min(a,b))throw Error('L’épaisseur doit être inférieure à la moitié du plus petit côté.');bi=a-2*t;hi=b-2*t;}A=a*b-bi*hi;Ix=(a*b**3-bi*hi**3)/12;Iy=(b*a**3-hi*bi**3)/12;cx=a/2;cy=b/2;}else throw Error('Section inconnue.');return checked({A,Ix,Iy,Wx:Ix/cy,Wy:Iy/cx,rx:Math.sqrt(Ix/A),ry:Math.sqrt(Iy/A)});}
function buckling(E,I,A,L,K,F,limit){E=p(E,'E')*1000;I=p(I,'I');A=p(A,'A');L=p(L,'L');K=p(K,'K');F=p(F,'La charge');const effective=K*L,critical=Math.PI**2*E*I/effective**2,stress=critical/A,r=Math.sqrt(I/A);let elastic=null;if(String(limit??'').trim())elastic=stress<=p(limit,'La limite de proportionnalité');return checked({effective,critical,stress,r,slender:effective/r,ratio:critical/F,elastic});}
function spring(d,D,n,G,L,s){d=p(d,'Le diamètre du fil');D=p(D,'Le diamètre moyen');n=p(n,'Le nombre de spires actives');G=p(G,'G')*1000;L=p(L,'La longueur libre');s=p(s,'La compression',true);const index=D/d;if(index<4||index>12)throw Error('Ce modèle est limité à un indice D/d compris entre 4 et 12.');const solid=(n+2)*d;if(L<=solid)throw Error('La longueur libre doit dépasser la hauteur à spires jointives.');if(s>=L-solid)throw Error('Compression à spires jointives ou au-delà : réduisez la course.');const rate=G*d**4/(8*D**3*n),force=rate*s,wahl=(4*index-1)/(4*index-4)+.615/index;return checked({index,rate,force,stress:wahl*8*force*D/(Math.PI*d**3),solid,length:L-s,reserve:L-s-solid,energy:force*s/2000,wahl});}
root.DesignTools={section,buckling,spring};if(typeof module==='object')module.exports=root.DesignTools;
})(typeof window==='undefined'?globalThis:window);
if(typeof window!=='undefined'){
Object.assign(info,{
 sections:['Aire & moments quadratiques','Rectangle : A=bh ; Ix=bh³/12 ; Iy=hb³/12. Cercle : A=πD²/4 ; Ix=Iy=πD⁴/64. Sections creuses : différence des sections concentriques extérieure et intérieure. Wx=Ix/(h/2), Wy=Iy/(b/2) ; r=√(I/A).','Axes x horizontal et y vertical passant par le centre. Sections idéales, tubes rectangulaires à angles vifs, épaisseur uniforme. Les rayons réels des profilés ne sont pas inclus. Moments d’aire en mm⁴, pas inerties de masse. Ces valeurs ne sont pas des constantes de torsion.','Penn State — Centroid and Moment of Inertia Table','https://adaptivemap.ma.psu.edu/websites/centroidtables/centroids2D/centroids2D.html'],
 flambement:['Charge critique d’Euler','L efficace = KL ; Fcr=π²EI/(KL)² ; r=√(I/A) ; λ=KL/r ; σcr=Fcr/A. E converti de GPa en N/mm².','Colonne idéale, droite, prismatique, charge centrée, comportement élastique. I et K doivent correspondre au même plan de flambement ; vérifier les deux axes. K théoriques sans déplacement latéral : articulé–articulé 1 ; encastré–libre 2 ; encastré–encastré 0,5 ; encastré–articulé ≈0,7. La limite de proportionnalité est facultative ; sans elle, le domaine élastique n’est pas vérifié. Fcr/F est un rapport théorique, pas un coefficient de sécurité réglementaire. Défauts, flambement local, plasticité et assemblages réels non vérifiés.','Penn State — Column Buckling: Design using Euler Theory','https://sites.esm.psu.edu/courses/emch213d/tutorials/design_notes/docs/design_buckling/bucdes1u.pdf'],
 ressorts:['Raideur & effort du ressort','C=D/d ; k=Gd⁴/(8D³Na) ; F=ks ; Kw=(4C−1)/(4C−4)+0,615/C ; τ=Kw·8FD/(πd³). Extrémités rapprochées et meulées : Nt=Na+2 ; hauteur jointive ≈Nt·d. Énergie=Fs/2.','Ressort cylindrique de compression en fil rond, spires à faible angle, matériau élastique. D est le diamètre moyen, pas extérieur. Domaine choisi : 4≤D/d≤12. Hauteur jointive nominale sans tolérances ; la réserve calculée n’est pas une course de sécurité validée. Fatigue, flambement du ressort, contraintes admissibles, frottements et résonance non vérifiés.','Newcomb Spring / SMI — Compression Spring Stress','https://www.newcombspring.com/resources/compression-spring-stress']
});
window.syncDesign=function(){if(slug!=='sections')return;const s=v('dt_shape');for(const el of document.querySelectorAll('[data-shapes]'))el.hidden=!el.dataset.shapes.split(' ').includes(s);};
window.calcDesign=function(){syncDesign();run('out_design',()=>{let r,rows,note='';const x=id=>v('dt_'+id);if(slug==='sections'){const shape=x('shape');r=DesignTools.section(shape,x(shape==='circle'||shape==='tube'?'D':'b'),x(shape==='tube'?'d':'h'),x('t'));rows=[['Aire de la section',fmt(r.A,5),'mm²'],['Moment quadratique Ix',fmt(r.Ix,5),'mm⁴'],['Moment quadratique Iy',fmt(r.Iy,5),'mm⁴'],['Module de flexion Wx',fmt(r.Wx,5),'mm³'],['Module de flexion Wy',fmt(r.Wy,5),'mm³'],['Rayon de giration rx',fmt(r.rx,5),'mm'],['Rayon de giration ry',fmt(r.ry,5),'mm']];}
else if(slug==='flambement'){r=DesignTools.buckling(...['E','I','A','L','K','F','limit'].map(x));rows=[['Charge critique idéale',fmt(r.critical/1000,5),'kN'],['Rapport Fcr / charge appliquée',fmt(r.ratio,5)],['Contrainte critique idéale',fmt(r.stress,5),'MPa'],['Longueur efficace',fmt(r.effective),'mm'],['Élancement',fmt(r.slender,5)],['Domaine élastique',r.elastic===null?'Non vérifié':r.elastic?'Sous la limite saisie':'Limite dépassée : Euler inapplicable']];note=r.elastic===false?'La charge affichée est une valeur mathématique hors du domaine élastique saisi. Elle ne constitue pas une capacité portante.':'Valeur théorique d’Euler, sans réduction pour défauts ni coefficient réglementaire.';}
else{r=DesignTools.spring(...['d','D','n','G','L','s'].map(x));rows=[['Raideur',fmt(r.rate,5),'N/mm'],['Effort à la compression saisie',fmt(r.force,5),'N'],['Contrainte corrigée de Wahl',fmt(r.stress,5),'MPa'],['Longueur comprimée',fmt(r.length),'mm'],['Hauteur à spires jointives',fmt(r.solid),'mm'],['Réserve avant spires jointives',fmt(r.reserve),'mm'],['Énergie stockée',fmt(r.energy,6),'J'],['Indice D/d',fmt(r.index)]];note='Extrémités rapprochées et meulées. La contrainte calculée doit être comparée à une valeur admissible adaptée au matériau et au service.';}show('out_design',rows,note);});};
document.addEventListener('DOMContentLoaded',()=>{syncDesign();document.addEventListener('click',e=>{if(e.target.id==='preset-load')syncDesign();});const refs={sections:['Engineering Statics — sections composées','https://engineeringstatics.org/Chapter_10-moment-of-inertia-of-composite-shapes.html'],flambement:['Université de Ljubljana — Buckling of Columns','https://physics.fe.uni-lj.si/students/literatura/20131029083424925_2.pdf'],ressorts:['Lee Spring — géométrie et conception des ressorts','https://www.leespring.in/sites/default/files/pdf/LeeSpring-WhitePaper-SpringDesignGeneralConsideration-IN.pdf']};const pair=refs[slug];if(pair){const a=document.createElement('a');a.textContent=pair[0]+' ↗';a.href=pair[1];a.target='_blank';a.rel='noopener';document.querySelector('.reference').append(a);if(slug==='ressorts'){const link=document.createElement('a');link.href='https://www.wermkespring.com/spring-load/';link.textContent='Wermke Spring — raideur et effort ↗';link.target='_blank';link.rel='noopener';document.querySelector('.reference').append(document.createElement('br'),link);}}});
}
