/* Shared interface; numerical models remain in calculations.js and extensions.js. */
(()=>{
'use strict';
const groups={puissance:'Transmission',dilatation:'Thermique',ajustements:'Assemblages',vissage:'Assemblages',clavette:'Assemblages',taraudage:'Assemblages',engrenages:'Transmission',roulements:'Transmission',courroie:'Transmission',torsion:'Résistance',rdm:'Résistance',thermo:'Thermique',verins:'Fluides',fluides:'Fluides',pompes:'Fluides',vibrations:'Dynamique'};
const paths={puissance:'M4 12h16M15 7l5 5-5 5M8 4a8 8 0 0 0 0 16',dilatation:'M3 9h18v6H3zM3 4v3m18-3v3M7 4h10',index:'M3 11L12 3l9 8M6 10v11h12V10M10 21v-7h4v7',ajustements:'M4 4h16v16H4zM8 8h8v8H8z',vissage:'M8 3h8v5H8zM10 8v13h4V8M9 12h6m-6 4h6',clavette:'M4 9h16v8H4zM8 9V5h8v4',taraudage:'M7 3v18m10-18v18M7 5l10 4M7 10l10 4M7 15l10 4',engrenages:'M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10l2 2M5 19l2-2M17 7l2-2M18 12a6 6 0 1 1-12 0 6 6 0 1 1 12 0M14 12a2 2 0 1 1-4 0 2 2 0 1 1 4 0',roulements:'M21 12a9 9 0 1 1-18 0 9 9 0 1 1 18 0M16 12a4 4 0 1 1-8 0 4 4 0 1 1 8 0M12 5v1m0 12v1M5 12h1m12 0h1',courroie:'M7 4h10a4 4 0 0 1 0 8H7a4 4 0 0 1 0-8M7 4v8m10-8v8M4 20h16',torsion:'M5 7h14v10H5zM3 12h18M17 3l3 2-3 2m3-2H9',rdm:'M3 13h18M5 14l-3 6h6zM19 14l-3 6h6zM12 2v8m-3-3 3 3 3-3',thermo:'M10 4a2 2 0 0 1 4 0v10a4 4 0 1 1-4 0V4M12 8v9',verins:'M3 6h13v12H3zM10 6v12m0-6h12',fluides:'M2 7h20M2 17h20M5 12h13m-3-3 3 3-3 3',pompes:'M18 12a6 6 0 1 1-12 0 6 6 0 1 1 12 0M10 9l5 3-5 3zM2 12h4m12 0h4',vibrations:'M2 12c3-14 5-14 8 0s5 14 8 0 3-8 4-8'};
const icon=key=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[key]||paths.index}"/></svg>`;
const keyOf=a=>a.getAttribute('href').split('/').pop().replace('.html','');
let saved;try{saved=localStorage.getItem('clemeca_theme');}catch{}
const mq=typeof matchMedia==='function'?matchMedia('(prefers-color-scheme: dark)'):null;
document.documentElement.dataset.theme=saved|| (mq?.matches?'dark':'light');
document.addEventListener('DOMContentLoaded',()=>{
 const header=document.querySelector('header');if(header){const toggle=document.createElement('button');toggle.className='theme-toggle';toggle.type='button';const update=()=>{const dark=document.documentElement.dataset.theme==='dark';toggle.innerHTML=dark?'☀':'☾';toggle.setAttribute('aria-label',dark?'Activer le mode clair':'Activer le mode sombre');toggle.title=toggle.getAttribute('aria-label');toggle.setAttribute('aria-pressed',String(dark));};update();toggle.onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';try{localStorage.setItem('clemeca_theme',document.documentElement.dataset.theme);}catch{}update();};header.append(toggle);}
 document.querySelectorAll('nav a').forEach(a=>{const n=a.querySelector('.nav-number');if(n){n.className='nav-symbol';n.innerHTML=icon(keyOf(a));}});
 document.querySelectorAll('.tile').forEach(tile=>{const key=keyOf(tile);tile.dataset.group=groups[key];tile.querySelector('.icon').innerHTML=icon(key);const badge=document.createElement('span');badge.className='tool-domain';badge.textContent=groups[key];tile.append(badge);});
 const home=document.querySelector('main.home');if(home){home.querySelector('h1').innerHTML='Votre atelier.<br><span>Tous les calculs, au même endroit.</span>';const intro=home.querySelector('.card>.subtle');if(intro)intro.textContent='16 outils pour dimensionner, comprendre et vérifier.';
 const bar=document.createElement('div');bar.className='library-controls';bar.innerHTML='<label class="search-label" for="tool-search">Rechercher un calculateur</label><div class="search-wrap"><span aria-hidden="true">⌕</span><input id="tool-search" type="search" placeholder="Un outil, un domaine, une formule…" autocomplete="off"></div><div class="domain-filters" role="group" aria-label="Filtrer par domaine"></div><p id="tool-count" role="status" aria-live="polite"></p>';
 const tiles=home.querySelector('.tiles');tiles.before(bar);const empty=document.createElement('p');empty.className='search-empty';empty.textContent='Aucun outil ne correspond. Essayez un autre mot ou un autre domaine.';empty.hidden=true;tiles.after(empty);let selected='Tous';const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();function filter(){const q=normalize(bar.querySelector('input').value.trim());let n=0;tiles.querySelectorAll('.tile').forEach(t=>{t.hidden=!(selected==='Tous'||t.dataset.group===selected)||!normalize(t.textContent).includes(q);if(!t.hidden)n++;});bar.querySelector('#tool-count').textContent=n+' outil'+(n>1?'s':'')+(selected==='Tous'?'':' · '+selected);empty.hidden=n>0;}
 for(const group of ['Tous',...new Set(Object.values(groups))]){const b=document.createElement('button');b.type='button';b.textContent=group;b.setAttribute('aria-pressed',String(group===selected));b.onclick=()=>{selected=group;bar.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();};bar.querySelector('.domain-filters').append(b);}bar.querySelector('input').addEventListener('input',filter);filter();}
 // Existing diagrams: keep focus linked to the matching geometric parameter.
 const figure=document.querySelector('.calc-diagram');if(figure){const card=figure.closest('.card');card.addEventListener('focusin',e=>figure.querySelectorAll('[data-field]').forEach(g=>g.classList.toggle('highlight',g.dataset.field===e.target.id)));}
 document.querySelectorAll('.card').forEach(card=>card.addEventListener('focusout',()=>card.querySelectorAll('.highlight').forEach(g=>g.classList.remove('highlight'))));
 if(['fluides','vibrations'].includes(slug))setupCurve();
 if(slug==='verins')setupCylinder();
 if(slug==='engrenages')setupGears();
});
function setupGears(){const figure=document.querySelector('.calc-diagram'),card=figure.closest('.card');function draw(){try{const r=Calculations.gear(v('gear_m'),v('gear_z1'),v('gear_z2'),v('gear_n1')),sum=r.d1+r.d2,r1=110*r.d1/sum,r2=110*r.d2/sum,x1=140+r1,x2=x1+r1+r2;figure.hidden=false;figure.querySelector('svg').innerHTML=`<title>Diamètres primitifs des engrenages, proportions selon les nombres de dents</title><g class="drawing"><g data-field="gear_z1"><circle class="part" cx="${x1}" cy="100" r="${r1}"/><text x="${x1}" y="100">z₁</text></g><g data-field="gear_z2"><circle class="part" cx="${x2}" cy="100" r="${r2}"/><text x="${x2}" y="100">z₂</text></g><g data-field="gear_m"><path d="M${x1} 240H${x2}"/><text x="250" y="268">a = ${fmt(r.a)} mm</text></g></g>`;figure.querySelector('svg').setAttribute('viewBox','0 -30 500 320');figure.querySelector('figcaption').innerHTML='Diamètres primitifs : '+fmt(r.d1)+' et '+fmt(r.d2)+' mm.<span>Proportions des cercles liées aux nombres de dents. Dentures non représentées.</span>';}catch{figure.hidden=true;}}card.addEventListener('input',draw);card.addEventListener('change',draw);document.addEventListener('click',e=>{if(e.target.id==='preset-load')draw();});draw();}
function setupCylinder(){const figure=document.querySelector('.calc-diagram'),card=figure.closest('.card');function draw(){const D=Number(v('ex_D').replace(',','.')),d=Number(v('ex_d').replace(',','.'));if(!(D>0&&d>=0&&d<D)){figure.hidden=true;return;}figure.hidden=false;const rod=90*d/D,inside=v('ex_mode')==='in',piston=inside?150:260;figure.querySelector('svg').innerHTML=`<title>Vérin : proportions de la tige et sens du mouvement</title><g class="drawing"><g data-field="ex_D"><rect x="70" y="65" width="270" height="90" rx="6"/><text x="205" y="45">D = ${D} mm</text></g><g data-field="ex_d"><rect x="${piston}" y="${110-rod/2}" width="${440-piston}" height="${rod}" class="part"/><text x="390" y="180">d = ${d} mm</text></g><rect x="${piston}" y="65" width="12" height="90" class="part"/><g data-field="ex_mode"><path d="${inside?'M240 200H160l10-6m-10 6 10 6':'M160 200H240l-10-6m10 6-10 6'}" class="effort"/><text x="200" y="225">${inside?'Rentrée':'Sortie'} de tige</text></g></g>`;figure.querySelector('svg').setAttribute('viewBox','0 0 500 245');}card.addEventListener('input',draw);card.addEventListener('change',draw);document.addEventListener('click',e=>{if(e.target.id==='preset-load')draw();});draw();}
function setupCurve(){const card=document.querySelector('main .card'),section=document.createElement('section');section.className='curve-panel';section.setAttribute('aria-label','Exploration du calcul');const vib=slug==='vibrations',field=vib?'ex_f':'ex_Q',unit=vib?'Hz':'m³/h';section.innerHTML=`<div class="curve-head"><div><h3>${vib?'Explorer la réponse vibratoire':'Explorer les pertes de charge'}</h3><p>${vib?'Amplitude crête selon la fréquence de la force.':'Perte de pression selon le débit, à géométrie constante.'}</p></div><span class="curve-badge">Exploration</span></div><div class="curve-plot"></div><label for="curve-range">${vib?'Fréquence d’excitation':'Débit'} <output id="curve-value"></output></label><input type="range" id="curve-range" min="0" step="any"><p class="curve-note"></p>`;card.after(section);const range=section.querySelector('input'),plot=section.querySelector('.curve-plot'),note=section.querySelector('.curve-note');let busy=false,max=0,scaleTop=1;
 function result(x){const a=id=>v('ex_'+id);return vib?ExtraCalculations.vibration(a('m'),a('k'),a('c'),a('F'),x).amplitude*1000:ExtraCalculations.pipe(x,...['D','L','rho','mu','rough','K'].map(a)).pressure/1000;}
 function draw(){if(busy)return;const valid=$('out_extra').dataset.valid==='true';section.hidden=!valid;if(!valid)return;const current=Number(v(field).replace(',','.'));try{const fn=vib?Math.sqrt(Number(v('ex_k').replace(',','.'))/Number(v('ex_m').replace(',','.')))/(2*Math.PI):0;max=Math.max(vib?3*fn:1,2*current);if(!(max>0&&Number.isFinite(max)))return;range.max=max;range.value=current;section.querySelector('output').textContent=fmt(current,4)+' '+unit;const xs=Array.from({length:241},(_,i)=>i*max/240);if(vib){xs.push(fn);const c=Number(v('ex_c').replace(',','.')),m=Number(v('ex_m').replace(',','.')),k=Number(v('ex_k').replace(',','.')),z=c/(2*Math.sqrt(k*m));if(z<Math.SQRT1_2)xs.push(fn*Math.sqrt(1-2*z*z));}if(!vib){const mu=Number(v('ex_mu').replace(',','.'))/1000,D=Number(v('ex_D').replace(',','.'))/1000,rho=Number(v('ex_rho').replace(',','.'));for(const Re of [2300,3000,3999,4000]){const q=Re*mu*Math.PI*D*3600/(4*rho);if(q<=max)xs.push(q);}}xs.push(current);xs.sort((a,b)=>a-b);const points=xs.map(x=>{try{return [x,result(x)];}catch{return [x,null];}});const top=Math.max(...points.map(p=>p[1]||0),1e-9)*1.12;scaleTop=top;let path='',pen=false;for(const [x,y] of points){if(y===null){pen=false;continue;}path+=(pen?'L':'M')+(55+600*x/max).toFixed(2)+' '+(220-170*y/top).toFixed(2)+' ';pen=true;}const y=result(current);plot.innerHTML=`<svg viewBox="0 0 700 275" role="img" aria-labelledby="curve-title"><title id="curve-title">${vib?'Amplitude en millimètres selon la fréquence en hertz':'Perte de pression en kilopascals selon le débit en mètres cubes par heure'}. Valeur choisie : ${fmt(y,4)} ${vib?'mm':'kPa'}.</title><path class="chart-grid" d="M55 50H655M55 135H655M55 220H655"/><path class="chart-axis" d="M55 40V220H660"/><text x="55" y="27">${vib?'Amplitude (mm)':'Δp (kPa)'}</text><text x="55" y="245">0</text><text x="590" y="245">${fmt(max,2)} ${unit}</text><text x="60" y="65">${fmt(top,3)}</text><path class="chart-line" d="${path}"/><circle class="chart-point" cx="${55+600*current/max}" cy="${220-170*y/top}" r="5"/></svg>`;note.textContent=vib?(Number(v('ex_c').replace(',','.'))===0?'Sans amortissement : la courbe est interrompue à la résonance ; le pic n’est pas borné.':'Courbe échantillonnée, avec le pic théorique inclus. Le point indique le calcul actuel.'):'La courbe est interrompue dans la zone transitoire (2 300 ≤ Re < 4 000).';}catch{section.hidden=true;}}
 range.addEventListener('input',()=>{const value=Number(range.value);$(field).value=String(value);busy=true;calcExtra();busy=false;section.querySelector('output').textContent=fmt(value,4)+' '+unit;try{const y=result(value);note.textContent=(vib?'Amplitude : ':'Perte de pression : ')+fmt(y,5)+' '+(vib?'mm':'kPa');}catch(e){note.textContent=e.message;} // Keep the same scale while the user drags.
 const point=plot.querySelector('.chart-point');if(point){try{const y=result(value);point.setAttribute('cx',55+600*value/max);point.setAttribute('cy',220-170*y/scaleTop);point.style.opacity='1';}catch{point.style.opacity='0';}}});range.addEventListener('change',draw);
 card.addEventListener('input',()=>{section.hidden=true;});card.addEventListener('change',()=>{section.hidden=true;});document.addEventListener('click',e=>{if(e.target.closest('button[onclick="calcExtra()"]'))draw();if(e.target.id==='preset-load')section.hidden=true;});draw();
}
})();
