/* SI internally; inputs use the units stated in each form. */
(function(root){
'use strict';
const base=typeof module!=='undefined'?require('./calculations.js'):root.Calculations;
const p=base.pos;
function checked(r){for(const x of Object.values(r))if(typeof x==='number'&&!Number.isFinite(x))throw Error('Valeurs hors du domaine numérique.');return r;}
function efficiency(x,name){x=p(x,name);if(x>100)throw Error(name+' doit être compris entre 0 exclu et 100 %.');return x/100;}
const X={
 cylinder(D,d,pressure,back,friction,mode){D=p(D,'Le diamètre du piston')/1000;d=p(d,'Le diamètre de tige',true)/1000;pressure=p(pressure,'La pression',true)*1e5;back=p(back,'La contre-pression',true)*1e5;friction=p(friction,'Le frottement',true);if(d>=D)throw Error('La tige doit être plus petite que le piston.');if(!['out','in'].includes(mode))throw Error('Sens inconnu.');const A=Math.PI*D*D/4,B=Math.PI*(D*D-d*d)/4,drive=mode==='out'?A:B,opposed=mode==='out'?B:A;return checked({area:drive*1e6,theoretical:pressure*drive,backForce:back*opposed,force:pressure*drive-back*opposed-friction});},
 pipe(Q,D,L,rho,mu,rough,K){Q=p(Q,'Le débit',true)/3600;D=p(D,'Le diamètre')/1000;L=p(L,'La longueur',true);rho=p(rho,'La masse volumique');mu=p(mu,'La viscosité')/1000;rough=p(rough,'La rugosité',true)/1000;K=p(K,'La somme des coefficients K',true);if(rough/D>.05)throw Error('Rugosité relative supérieure à 5 % : hors domaine retenu.');const velocity=4*Q/(Math.PI*D*D),Re=rho*velocity*D/mu;if(Q===0)return {velocity:0,Re:0,factor:0,linear:0,local:0,pressure:0,head:0,regime:'Au repos'};if(Re>=2300&&Re<4000)throw Error('Re = '+Math.round(Re)+' : régime transitoire (2 300 à 4 000). Les pertes ne sont pas estimées dans cette zone.');let factor;if(Re<2300)factor=64/Re;else{let lo=1,hi=1024;for(let i=0;i<90;i++){const x=(lo+hi)/2,res=x+2*Math.log10(rough/(3.7*D)+2.51*x/Re);if(res>0)hi=x;else lo=x;}factor=1/((lo+hi)/2)**2;}const dynamic=rho*velocity*velocity/2,linear=factor*L/D*dynamic,local=K*dynamic,pressure=linear+local;return checked({velocity,Re,factor,linear,local,pressure,head:pressure/(rho*9.81),regime:Re<2300?'Laminaire':'Turbulent'});},
 pump(Q,H,rho,etaPump,etaMotor){Q=p(Q,'Le débit')/3600;H=p(H,'La hauteur manométrique');rho=p(rho,'La masse volumique');const ep=efficiency(etaPump,'Le rendement pompe'),em=efficiency(etaMotor,'Le rendement moteur'),hydraulic=rho*9.81*Q*H,shaft=hydraulic/ep;return checked({hydraulic,shaft,electric:shaft/em,pressure:rho*9.81*H,overall:ep*em*100});},
 vibration(m,k,c,F,f){m=p(m,'La masse');k=p(k,'La raideur');c=p(c,'L’amortissement',true);F=p(F,'La force',true);f=p(f,'La fréquence',true);const omega0=Math.sqrt(k/m),fn=omega0/(2*Math.PI),zeta=c/(2*Math.sqrt(k*m)),omega=2*Math.PI*f,den=Math.hypot(k-m*omega*omega,c*omega);if(c===0&&Math.abs(omega-omega0)<=1e-12*omega0&&F>0)throw Error('Résonance sans amortissement : aucune amplitude permanente finie. Ajoutez un amortissement physique.');return checked({fn,period:1/fn,zeta,critical:2*Math.sqrt(k*m),fd:zeta<1?fn*Math.sqrt(1-zeta*zeta):null,amplitude:F===0?0:F/den,phase:F===0?0:Math.atan2(c*omega,k-m*omega*omega)*180/Math.PI,regime:zeta===0?'Non amorti':Math.abs(zeta-1)<1e-12?'Critique':zeta<1?'Sous-amorti':'Sur-amorti'});}
};
root.ExtraCalculations=X;if(typeof module!=='undefined')module.exports=X;
})(typeof globalThis!=='undefined'?globalThis:this);
