'use strict';
Object.assign(info,{
 verins:['Force disponible du vérin','A = πD²/4 ; B = π(D² − d²)/4. Sortie : F = pA − pᵣB − Ff. Rentrée : F = pB − pᵣA − Ff. 1 bar = 100 000 Pa.','Pressions relatives, effort dans le sens choisi, frottement opposé au déplacement. Une force négative indique que le mouvement demandé ne peut pas être assuré avec ces valeurs. Modèle quasi statique ; flambement de tige, accélération et charges latérales non vérifiés.','Festo — vérins, surfaces actives et frottement','https://labvolt.festo.com/downloads/89791_F0.pdf'],
 fluides:['Écoulement & pertes de charge','v = 4Q/(πD²) ; Re = ρvD/μ ; Δp = (λL/D + ΣK)ρv²/2 ; h = Δp/(ρg). λ = 64/Re en laminaire ; en turbulent : 1/√λ = −2log₁₀(ε/(3,7D) + 2,51/(Re√λ)).','Régime permanent établi, conduite circulaire pleine, fluide newtonien incompressible. Facteur de Darcy (pas Fanning). Laminaire Re < 2 300 ; turbulent Re ≥ 4 000. Zone transitoire exclue. Rugosité relative ≤ 5 %. Les K doivent provenir de données adaptées au régime et être rapportés à la vitesse saisie. La perte de charge exclut le dénivelé.','NIST TN 2294 — Reynolds, pertes et corrélation de Colebrook','https://nvlpubs.nist.gov/nistpubs/TechnicalNotes/NIST.TN.2294.pdf'],
 pompes:['Puissances de pompage','P hydraulique = ρgQH ; P arbre = P hydraulique/η pompe ; P électrique = P arbre/η moteur ; Δp équivalente = ρgH. g = 9,81 m/s².','Fluide incompressible, débit et hauteur positifs. Rendements au point de fonctionnement, saisis séparément. La hauteur totale inclut déjà les pertes : ne pas les compter deux fois. Ne sélectionne pas un modèle de pompe et ne vérifie pas la cavitation (NPSH), la courbe réseau ni les transitoires.','U.S. Department of Energy — Improving Pumping System Performance','https://www1.eere.energy.gov/manufacturing/tech_assistance/pdfs/pump.pdf'],
 vibrations:['Réponse harmonique & fréquence propre','ω₀ = √(k/m) ; f₀ = ω₀/(2π) ; ζ = c/(2√(km)) ; f amortie = f₀√(1−ζ²) pour ζ < 1. X = F₀/√((k−mω²)²+(cω)²), avec ω = 2πf. Retard de phase = atan2(cω, k−mω²).','Système linéaire à un degré de liberté, amortissement visqueux, force harmonique appliquée à la masse (pas excitation du support). X est une amplitude crête, pas crête-à-crête. Réponse forcée permanente ; le transitoire et les conditions initiales ne sont pas inclus. Sans amortissement, la résonance ne donne pas de réponse permanente finie.','P. Steeneken, TU Delft — Forced vibrations, équation 13.65','https://eng.libretexts.org/Bookshelves/Mechanical_Engineering/Introductory_Dynamics%3A_2D_Kinematics_and_Kinetics_of_Point_Masses_and_Rigid_Bodies_%28Steeneken%29/04%3A_Vibrations_and_Strategy/13%3A_Vibrations/13.04%3A_Forced_vibrations']
});
function calcExtra(){run('out_extra',()=>{
 const x=id=>v('ex_'+id),X=ExtraCalculations;let r,rows,note='';
 if(slug==='verins'){r=X.cylinder(...['D','d','p','back','friction','mode'].map(x));rows=[['Force disponible dans le sens choisi',fmt(r.force),'N'],['Force théorique d’alimentation',fmt(r.theoretical),'N'],['Effort de contre-pression',fmt(r.backForce),'N'],['Surface motrice',fmt(r.area),'mm²']];if(r.force<=0)note='Force disponible nulle ou négative : le déplacement demandé n’est pas assuré.';}
 else if(slug==='fluides'){r=X.pipe(...['Q','D','L','rho','mu','rough','K'].map(x));rows=[['Perte de pression totale',fmt(r.pressure/1000),'kPa'],['Hauteur perdue',fmt(r.head),'m de fluide'],['Vitesse moyenne',fmt(r.velocity),'m/s'],['Nombre de Reynolds',fmt(r.Re,0)],['Régime',r.regime],['Facteur de Darcy λ',r.Re===0?'Sans objet':fmt(r.factor,6)],['Pertes linéaires',fmt(r.linear/1000),'kPa'],['Pertes singulières',fmt(r.local/1000),'kPa']];}
 else if(slug==='pompes'){r=X.pump(...['Q','H','rho','ep','em'].map(x));rows=[['Puissance électrique absorbée',fmt(r.electric/1000),'kW'],['Puissance à l’arbre',fmt(r.shaft/1000),'kW'],['Puissance hydraulique utile',fmt(r.hydraulic/1000),'kW'],['Rendement global',fmt(r.overall),'%'],['Pression équivalente à H',fmt(r.pressure/1e5),'bar']];}
 else if(slug==='vibrations'){r=X.vibration(...['m','k','c','F','f'].map(x));rows=[['Amplitude crête de déplacement',fmt(r.amplitude*1000,5),'mm'],['Fréquence propre non amortie',fmt(r.fn,5),'Hz'],['Taux d’amortissement ζ',fmt(r.zeta,5)],['Régime libre associé',r.regime],['Fréquence libre amortie',r.fd===null?'Sans oscillation':fmt(r.fd,5),r.fd===null?'':'Hz'],['Amortissement critique',fmt(r.critical),'N·s/m'],['Retard sur la force',x('F').replace(',','.')*1===0?'Sans objet':fmt(r.phase),'°']];if(x('c')*1===0)note='Sans amortissement, la réponse libre persiste : cette amplitude décrit seulement la composante forcée.';}
 else throw Error('Calculateur inconnu.');show('out_extra',rows,note);
 });}
document.addEventListener('DOMContentLoaded',()=>{if(slug==='fluides'){const a=document.createElement('a');a.href='https://www.energy.gov/ehss/articles/doe-hdbk-10123-92';a.textContent='DOE — Darcy–Weisbach et pertes singulières ↗';a.target='_blank';a.rel='noopener';a.style.display='block';a.style.marginTop='12px';document.querySelector('.reference').append(a);}});
