/* Pure models: kW, N·m, rpm; mm, °C and µm/m/K. */
(function(root){
'use strict';
const C=typeof module==='object'?require('./calculations.js'):root.Calculations;
function finite(r){if(Object.values(r).some(x=>!Number.isFinite(x)))throw Error('Valeurs hors du domaine numérique.');return r;}
function power(mode,a,b){let P,T,n;if(mode==='P'){T=C.pos(a,'Le couple',true);n=C.pos(b,'La vitesse',true);P=T*(n/60)*2*Math.PI/1000;}else if(mode==='T'){P=C.pos(a,'La puissance',true);n=C.pos(b,'La vitesse');T=P*1000/(n/60*2*Math.PI);}else if(mode==='n'){P=C.pos(a,'La puissance',true);T=C.pos(b,'Le couple');n=P*1000/T*60/(2*Math.PI);}else throw Error('Mode inconnu.');return finite({P,T,n,omega:n/60*2*Math.PI});}
function expansion(mode,L,alpha,T1,value){L=C.pos(L,'La dimension initiale');alpha=C.num(alpha,'Le coefficient');T1=C.num(T1,'La température initiale');value=C.num(value,'La valeur recherchée');if(T1< -273.15)throw Error('Température inférieure au zéro absolu.');let T2,delta;if(mode==='delta'){T2=value;delta=L*alpha*1e-6*(T2-T1);}else if(mode==='T2'){if(alpha===0)throw Error('Un coefficient nul ne permet pas de déterminer une température.');delta=value;T2=T1+delta/(L*alpha*1e-6);}else throw Error('Mode inconnu.');if(T2< -273.15)throw Error('Température inférieure au zéro absolu.');const final=L+delta;if(final<=0)throw Error('La dimension finale doit rester positive.');return finite({delta,final,T2,dT:T2-T1,strain:delta/L});}
root.PracticalCalculations={power,expansion};if(typeof module==='object')module.exports=root.PracticalCalculations;
})(typeof window==='undefined'?globalThis:window);
if(typeof window!=='undefined'){
Object.assign(info,{
 puissance:['Puissance, couple & vitesse','P = Tω ; ω = 2πn/60 ; P(kW) = T(N·m) × 2π × n(tr/min) / 60 000.','Grandeurs positives ou nulles sur un même arbre. Puissance mécanique, pas électrique. Pas de pertes ni de rendement ajoutés. À vitesse nulle, le couple ne peut pas être déduit de la puissance ; à couple nul, la vitesse ne peut pas être déduite. Ne dimensionne pas un moteur.','OpenStax — Work and Power for Rotational Motion','https://openstax.org/books/university-physics-volume-1/pages/10-8-work-and-power-for-rotational-motion'],
 dilatation:['Dimension & température','ΔL = αL₀(T₂ − T₁) ; L₂ = L₀ + ΔL ; T₂ = T₁ + ΔL/(αL₀). Le coefficient saisi en µm/m/K est multiplié par 10⁻⁶.','Dilatation libre, température uniforme, coefficient moyen constant sur l’intervalle. Approximation linéaire pour de petites déformations, sans contrainte ni changement de phase. Utilisez le coefficient de votre nuance et de votre plage de température. La valeur 12 est un exemple modifiable, pas une propriété universelle de l’acier.','OpenStax — Thermal Expansion','https://openstax.org/books/university-physics-volume-2/pages/1-3-thermal-expansion']
});
window.togglePractical=function(){if(slug==='puissance')for(const k of ['P','T','n'])$('pc_'+k).disabled=k===v('pc_mode');if(slug==='dilatation'){const inverse=v('dl_mode')==='T2';$('dl_T2').disabled=inverse;$('dl_delta').disabled=!inverse;}};
window.calcPractical=function(){togglePractical();run('out_practical',()=>{const X=PracticalCalculations;let r,rows,note='';if(slug==='puissance'){const m=v('pc_mode');r=X.power(m,...(m==='P'?['pc_T','pc_n']:m==='T'?['pc_P','pc_n']:['pc_P','pc_T']).map(v));$('pc_'+m).value=Number(r[m].toPrecision(12));const values={P:['Puissance mécanique',fmt(r.P,5),'kW'],T:['Couple',fmt(r.T,5),'N·m'],n:['Vitesse de rotation',fmt(r.n,5),'tr/min']};rows=[values[m],...Object.keys(values).filter(k=>k!==m).map(k=>values[k]),['Vitesse angulaire',fmt(r.omega,5),'rad/s']];}else{const m=v('dl_mode');r=X.expansion(m,v('dl_L'),v('dl_alpha'),v('dl_T1'),v(m==='delta'?'dl_T2':'dl_delta'));$('dl_'+m).value=Number(r[m].toPrecision(12));rows=m==='T2'?[['Température finale',fmt(r.T2,5),'°C']]:[['Variation de dimension',fmt(r.delta,6),'mm']];rows.push(['Dimension finale',fmt(r.final,6),'mm'],['Écart de température',fmt(r.dT,5),'K'],['Déformation thermique',fmt(r.strain*100,6),'%']);note=Math.abs(r.strain)>.01?'Déformation supérieure à 1 % : vérifiez la validité du modèle linéaire et du coefficient moyen.':r.delta<0?'Refroidissement ou coefficient négatif : la dimension diminue.':'La pièce est supposée libre de se dilater.';}show('out_practical',rows,note);});};
window.drawFitZones=function(){let fig=$('fit-zones');if(!fig){fig=document.createElement('figure');fig.id='fit-zones';fig.className='fit-zones';$('out_ajust').after(fig);}const nums=['EI_hole','ES_hole','EI_shaft','ES_shaft'].map(id=>C.num(v(id),'Écart')*1000);const lo=Math.min(0,...nums),hi=Math.max(0,...nums),span=hi-lo||1,y=x=>195-(x-lo)/span*120;const label=x=>escapeHTML(fmt(x,3));fig.hidden=false;fig.innerHTML='<h3>Zones de tolérance</h3><svg viewBox="0 0 500 265" role="img" aria-label="Zones de tolérance du trou et de l’arbre, écarts en micromètres"><title>Écarts par rapport au diamètre nominal, en µm</title><line x1="50" x2="450" y1="'+y(0)+'" y2="'+y(0)+'" stroke="currentColor" stroke-dasharray="5 5"/>'+[[110,nums[0],nums[1],'Trou','#0071e3'],[305,nums[2],nums[3],'Arbre','#ac53d4']].map(([x,a,b,name,color])=>'<rect x="'+x+'" y="'+y(b)+'" width="85" height="'+Math.max(.7,y(a)-y(b))+'" fill="'+color+'" fill-opacity=".23" stroke="'+color+'"/><text x="'+(x+42)+'" y="35" text-anchor="middle">'+name+'</text><text x="'+(x+42)+'" y="'+(y(b)-12)+'" text-anchor="middle">'+label(b)+'</text><text x="'+(x+42)+'" y="'+(y(a)+24)+'" text-anchor="middle">'+label(a)+'</text>').join('')+'<text x="250" y="252" text-anchor="middle">Écarts (µm) · pointillés = diamètre nominal</text></svg><figcaption>Même échelle pour les deux zones. Les valeurs indiquent leurs limites.</figcaption>';};
document.addEventListener('DOMContentLoaded',()=>{togglePractical();if(slug==='dilatation'){const a=document.createElement('a');a.href='https://emtoolbox.nist.gov/Faq/Faq.asp';a.textContent='NIST — coefficients moyens et correction thermique ↗';a.target='_blank';a.rel='noopener';document.querySelector('.reference')?.append(a);}if(slug==='ajustements'){drawFitZones();const out=$('out_ajust');new MutationObserver(()=>{if(out.dataset.valid!=='true')$('fit-zones').hidden=true;}).observe(out,{attributes:true,attributeFilter:['data-valid']});}});
}
