'use strict';
function notify(message){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';el.setAttribute('role','status');document.body.appendChild(el);}el.textContent=message;el.hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.hidden=true,3500);}
function readStore(key,fallback={}){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback;}catch{return fallback;}}
function writeStore(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{notify('L’enregistrement local est indisponible. Vous pouvez télécharger le rapport.');return false;}}
function reportSnapshot(){
 const outs=Array.from(document.querySelectorAll('main [id^="out_"][data-valid="true"]'));
 if(!outs.length)throw Error('Lancez un calcul valide avant de créer un rapport.');
 return {title:document.querySelector('h1').textContent.trim(),createdAt:new Date().toISOString(),tool:location.pathname.split('/').pop(),blocks:outs.map(el=>({inputs:JSON.parse(el.dataset.inputs||'[]'),text:el.innerText||el.textContent,rows:Array.from(el.querySelectorAll('.result-item')).map(r=>({label:r.querySelector('.result-label').textContent,value:r.querySelector('strong').textContent})),time:el.dataset.time})),formulas:info[slug]?.[1]||'',assumptions:info[slug]?.[2]||'',source:info[slug]?.[4]||'',include:{inputs:true,outputs:true},meta:{date:new Date().toLocaleDateString('en-CA')}};
}
function snapshotText(data,onlyResults=false){const lines=[data.title,'CléMéca · '+new Date(data.createdAt).toLocaleString('fr-FR')];for(const b of data.blocks||[]){if(!onlyResults&&data.include?.inputs!==false){lines.push('','PARAMÈTRES');for(const input of b.inputs)lines.push(input.label+' : '+input.value);}if(data.include?.outputs!==false){lines.push('','RÉSULTATS',b.text);}}if(!onlyResults){lines.push('','FORMULES',data.formulas,'','HYPOTHÈSES',data.assumptions);if(data.source)lines.push('Référence : '+data.source);for(const [key,label] of [['project','Projet'],['client','Client'],['operator','Opérateur'],['date','Date'],['location','Lieu'],['notes','Notes'],['signature','Signature']])if(data.meta?.[key])lines.push(label+' : '+data.meta[key]);}return lines.join('\n');}
function downloadText(text,name,type='text/plain;charset=utf-8'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copyText(text){try{await navigator.clipboard.writeText(text);notify('Copié.');}catch{downloadText(text,'clemeca-rapport.txt');notify('Copie indisponible : rapport téléchargé.');}}
function withSnapshot(fn){try{fn(reportSnapshot());}catch(e){notify(e.message);}}
function renderReportHistory(main){const records=readStore('clemeca_reports',[]);if(!records.length)return;const section=document.createElement('details');section.innerHTML='<summary>Mes rapports enregistrés sur cet appareil</summary>';const list=document.createElement('ul');list.className='report-list';for(const r of records){const li=document.createElement('li'),a=document.createElement('a');a.href='report.html?id='+encodeURIComponent(r.id);a.textContent=r.title;const small=document.createElement('small');small.textContent=new Date(r.createdAt).toLocaleString('fr-FR');a.appendChild(small);li.appendChild(a);list.appendChild(li);}section.appendChild(list);main.appendChild(section);}
function initReports(){
 const main=document.querySelector('main');if(!main)return;
 if(slug==='index'){renderReportHistory(main);return;}
 if(!info[slug])return;
 const bar=document.createElement('div');bar.className='report-actions result-actions';
 function button(label,action,primary=false){const b=document.createElement('button');b.type='button';b.className='btn'+(primary?'':' secondary');b.textContent=label;b.addEventListener('click',action);bar.appendChild(b);}
 button('Créer un rapport',()=>withSnapshot(data=>{const id=crypto.randomUUID();data.id=id;const drafts=readStore('clemeca_drafts');drafts[id]=data;if(writeStore('clemeca_drafts',drafts))location.href='report_builder.html?id='+encodeURIComponent(id);}),true);
 button('Copier les résultats',()=>withSnapshot(data=>copyText(snapshotText(data,true))));
 button('Copier le rapport',()=>withSnapshot(data=>copyText(snapshotText(data))));
 button('Télécharger',()=>withSnapshot(data=>{const format=document.getElementById('export-format').value;let text=snapshotText(data);if(format==='md')text='# '+data.title+'\n\n```text\n'+text.replace(/```/g,'')+'\n```';if(format==='csv'){const esc=x=>'"'+String(x).replace(/"/g,'""')+'"';const rows=[['Section','Champ','Valeur']];for(const b of data.blocks){for(const x of b.inputs)rows.push(['Entrée',x.label,x.value]);for(const x of b.rows)rows.push(['Résultat',x.label,x.value]);}rows.push(['Méthode','Formules',data.formulas],['Méthode','Hypothèses',data.assumptions]);text='\ufeff'+rows.map(row=>row.map(esc).join(';')).join('\r\n');}downloadText(text,'clemeca-'+slug+'.'+format);}));
 const select=document.createElement('select');select.id='export-format';select.setAttribute('aria-label','Format du téléchargement');select.style.width='auto';select.innerHTML='<option value="txt">Texte</option><option value="md">Markdown</option><option value="csv">CSV</option>';bar.appendChild(select);main.appendChild(bar);
 const presets=document.createElement('details');presets.innerHTML='<summary>Enregistrer ou retrouver mes paramètres</summary><div class="report-actions"><input id="preset-name" aria-label="Nom du jeu de paramètres" placeholder="Nom de vos paramètres"><button type="button" class="btn secondary" id="preset-save">Enregistrer</button><select id="preset-list" aria-label="Paramètres enregistrés"><option value="">Choisir des paramètres…</option></select><button type="button" class="btn secondary" id="preset-load">Charger</button></div>';main.appendChild(presets);
 function refresh(){const select=$('preset-list');select.innerHTML='<option value="">Choisir des paramètres…</option>';const all=readStore('clemeca_presets')[slug]||{};for(const name of Object.keys(all)){const option=document.createElement('option');option.value=option.textContent=name;select.appendChild(option);}}refresh();
 $('preset-save').onclick=()=>{const name=v('preset-name').trim();if(!name){notify('Donnez un nom à vos paramètres.');return;}const all=readStore('clemeca_presets'),values=Object.fromEntries(Array.from(document.querySelectorAll('main .card input,main .card select')).map(el=>[el.id,el.value]));all[slug]??={};Object.defineProperty(all[slug],name,{value:values,enumerable:true,writable:true,configurable:true});if(writeStore('clemeca_presets',all)){refresh();notify('Paramètres enregistrés.');}};
 $('preset-load').onclick=()=>{const values=readStore('clemeca_presets')[slug]?.[v('preset-list')];if(!values){notify('Choisissez des paramètres.');return;}for(const [id,value] of Object.entries(values))if($(id))$(id).value=value;currentUnit=v('unit_len')||'mm';rdmCurrentUnit=v('rdm_unit')||'mm';refreshISO();rdmLabels();rdmToggleSection();toggleFriction();toggleBelt();toggleIG();updateTapPitch();clearResults();notify('Paramètres chargés. Lancez le calcul.');};
}
document.addEventListener('DOMContentLoaded',initReports);
