/* Presentation only: the established vibration model remains unchanged. */
document.addEventListener('DOMContentLoaded',()=>{
 const card=document.querySelector('main>.card'),heading=document.querySelector('.page-heading');
 heading.querySelector('.eyebrow').innerHTML='LE LABORATOIRE <span>/ DYNAMIQUE</span>';
 heading.querySelector('h1').textContent='Comprendre le mouvement.';
 const intro=document.createElement('p');intro.className='studio-intro';intro.textContent='Vibrations · Explorez l’équilibre entre masse, raideur et amortissement.';heading.append(intro);
 card.querySelector('h2').remove();const description=card.querySelector(':scope > .subtle');description.className='studio-description';
 const form=card.querySelector('.row');form.classList.add('studio-parameters');const title=document.createElement('div');title.className='parameters-title';title.innerHTML='<span class="studio-kicker">01 / VOTRE SYSTÈME</span><h2>Les paramètres.</h2><p>Définissez le système et son excitation.</p>';form.prepend(title);
 const figure=card.querySelector('figure');figure.innerHTML=`<div class="diagram-heading"><span class="studio-kicker">MODÈLE À UN DEGRÉ DE LIBERTÉ</span><span class="model-chip">m · k · c</span></div><svg viewBox="0 0 560 245" role="img" aria-labelledby="oscillator-title"><title id="oscillator-title">Masse reliée à un support fixe par un ressort et un amortisseur, soumise à une force harmonique</title><defs><pattern id="support-hatch" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" stroke="currentColor" opacity=".2"/></pattern></defs><rect x="43" y="45" width="22" height="150" fill="url(#support-hatch)"/><g fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><path d="M65 45V195"/><g data-field="ex_k"><path d="M65 83H95l9-14 16 28 16-28 16 28 16-28 16 28 9-14H240"/><text x="145" y="48">k</text></g><g data-field="ex_c"><path d="M65 157H128m0-13v26h46v-26h-46m16 0v26m0-13h96"/><text x="150" y="199">c</text></g><g data-field="ex_m"><rect class="oscillator-mass" x="240" y="61" width="106" height="116" rx="20"/><text class="mass-label" x="293" y="126">m</text></g><g data-field="ex_F" class="force-arrow"><path d="M346 119H472l-10-7m10 7-10 7"/><text x="422" y="94">F₀ cos(2πft)</text></g><path class="displacement" d="M252 215H337l-8-5m8 5-8 5"/><text x="294" y="238">x(t)</text></g></svg><figcaption>Un système simple. Une réponse à explorer.<span>Schéma de principe · non à l’échelle</span></figcaption>`;
 const reference=document.querySelector('.reference');if(reference){reference.classList.add('studio-reference');reference.querySelector('summary').textContent='Comprendre les formules et les limites du modèle';}
 const plot=document.querySelector('.curve-plot');
 function polish(){const svg=plot?.querySelector('svg');if(!svg||svg.querySelector('.frequency-marker'))return;const range=document.getElementById('curve-range'),max=Number(range.max),m=Number(document.getElementById('ex_m').value),k=Number(document.getElementById('ex_k').value),fn=Math.sqrt(k/m)/(2*Math.PI);if(!(fn>=0&&fn<=max))return;const x=55+600*fn/max;const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('class','frequency-marker');g.innerHTML=`<path d="M${x} 48V220"/><text x="${x+7}" y="85">f₀ · ${fn.toLocaleString('fr-FR',{maximumFractionDigits:2})} Hz</text>`;svg.insertBefore(g,svg.querySelector('.chart-line'));}
 if(plot){new MutationObserver(polish).observe(plot,{childList:true});polish();}
});
